// CONSTANTS
export const GET_NEWS_PENDING = "NEWS::GET_NEWS_PENDING";
export const GET_NEWS_FILFULLED = "NEWS::GET_NEWS_FILFULLED";
export const GET_NEWS_REJECTED = "NEWS::GET_NEWS_REJECTED";

// USER INFO

// TRIGGERS
export const GET_NEWS_TRIGGER = "NEWS::GET_NEWS_TRIGGER";
