// CONSTANTS
export const GET_NEWS_PENDING = "NEWS::GET_NEWS_PENDING";
export const GET_NEWS_FILFULLED = "NEWS::GET_NEWS_FILFULLED";
export const GET_NEWS_REJECTED = "NEWS::GET_NEWS_REJECTED";

// LOGIN

export const LOGIN_PENDING = "LOGIN::LOGIN_PENDING";
export const LOGIN_FILFULLED = "LOGIN::LOGIN_FILFULLED";
export const LOGIN_REJECTED = "LOGIN::LOGIN_REJECTED";
export const LOGOUT_CONST = "LOGOUT_CONST";

// USER INFO

export const GET_USER_INFO_PENDING = "USER-INFO::GET_USER_INFO_PENDING";
export const GET_USER_INFO_FILFULLED = "USER-INFO::GET_USER_INFO_FILFULLED";
export const GET_USER_INFO_REJECTED = "USER-INFO::GET_USER_INFO_REJECTED";

// TRIGGERS
export const GET_NEWS_TRIGGER = "NEWS::GET_NEWS_TRIGGER";
export const LOGIN_TRIGGER = "LOGIN::LOGIN_TRIGGER";
export const GET_USER_INFO_TRIGGER = "USER-INFO::GET_USER_INFO_TRIGGER";
